<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readCloudConfiguration</value>
  <value name="encodeutf8">true</value>
  <value name="body">RmlsZSBwYWNrYWdlQ29uZmlnRGlyID0gU2VydmVyQVBJLmdldFBhY2thZ2VDb25maWdEaXIoUEFD
S0FHRV9OQU1FKTsNCg0KaWYgKHBhY2thZ2VDb25maWdEaXIgPT0gbnVsbCkgew0KCXNpbXBsZUxv
ZygicGFja2FnZSBjb25maWcgZGlyIGlzOiAiICsgcGFja2FnZUNvbmZpZ0Rpci50b1BhdGgoKS50
b1N0cmluZygpLCBudWxsLCBudWxsKTsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiVW5h
YmxlIHRvIHJlYWQgIiArIFBBQ0tBR0VfTkFNRSArICIgY29uZmlndXJhdGlvbiBmb2xkZXIiKTsN
Cn0NClBhdGggY29uZmlnRmlsZVBhdGggPSBQYXRocy5nZXQocGFja2FnZUNvbmZpZ0RpciArIEZp
bGUuc2VwYXJhdG9yICsgQ09ORklHX0ZJTEVfTkFNRSk7DQppZiAoIUZpbGVzLmV4aXN0cyhjb25m
aWdGaWxlUGF0aCkpIHsNCglzaW1wbGVMb2coImNvbmZpZyBmaWxlIGlzOiAiICsgY29uZmlnRmls
ZVBhdGgudG9TdHJpbmcoKSwgbnVsbCwgbnVsbCk7DQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oIlVuYWJsZSB0byBmaW5kIHRoZSBuZWVkZWQgIiArIENPTkZJR19GSUxFX05BTUUgKyAiIGlu
IHRoZSBjb25maWd1cmF0aW9uIGZvbGRlciIpOw0KfQ0KdHJ5IHsNCglTdHJpbmcgY29uZmlnQXNT
dHJpbmcgPSBuZXcgU3RyaW5nKEZpbGVzLnJlYWRBbGxCeXRlcyhjb25maWdGaWxlUGF0aCkpOw0K
CQ0KCWlmIChjb25maWdBc1N0cmluZyA9PSBudWxsIHx8IGNvbmZpZ0FzU3RyaW5nLmlzRW1wdHko
KSkgew0KCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRW1wdHkgY29uZmlndXJhdGlvbiBm
aWxlIGZvciAiICsgUEFDS0FHRV9OQU1FICsgIi4gVW5hYmxlIHRvIGNvbnRpbnVlIGluaXRpYWwg
Y29uZmlndXJhdGlvbi4iKTsNCgl9DQoNCgkvLyBwaXBlbGluZQ0KCUlEYXRhQ3Vyc29yIHBpcGVs
aW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJSURhdGFVdGlsLnB1dCggcGlwZWxp
bmVDdXJzb3IsICJjbG91ZEFwcENvbmZpZ3VyYXRpb24iLCBjb25maWdBc1N0cmluZyApOw0KCXBp
cGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCn0gY2F0Y2ggKElPRXhjZXB0aW9uIGUpIHsNCgl0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsNCn0=</value>
</Values>
